[package]
name = "numbers"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
subtraction_decisions = { path = "/Users/mstankus/Documents/repos/mstankus/r_ncgb/many_libs/subtraction_decisions" }
